# Generated by Django 5.0.2 on 2024-03-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='saving_info',
            new_name='savings_info',
        ),
    ]
